/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/staging/vintageTelevision.glb -d -t -v -p 4 
*/

import { useValue } from '@legendapp/state/react'
import { useGLTF } from '@react-three/drei'
import { type ThreeElements, useThree } from '@react-three/fiber'
import { useEffect, useRef } from 'react'
import { DoubleSide, type Group, type Mesh, type MeshStandardMaterial, ShaderMaterial, Uniform, Vector2, Vector3 } from 'three'
import { FullScreenQuad, type GLTF } from 'three-stdlib'

import type { GroupProps } from '~/types'

import { useFramerate } from '~/hooks/useFramerate'
import SpotifyLogo from '~/models/Spotify'
import { $sceneStore, $sceneStoreActions } from '~/stores/scene'

import PortalMaterial, { type PortalProps } from "../PortalMaterial"
import frag from "../TransitionMaterial/frag.glsl"
import vert from "../TransitionMaterial/vert.glsl"
import transitionFrag from "./frag.glsl"
import PlaylistsScene from './Playlists'
import transitionVert from "./vert.glsl"

type GLTFResult = GLTF & {
	materials: {
		['TV_Chayka-206']: MeshStandardMaterial
	}
	nodes: {
		TV: Mesh
		TVSCREEN: Mesh
		TVSCREENBEZEL: Mesh
	}
}

export default function InitialScene(props: GroupProps) {
	const { materials, nodes } = useGLTF('models/tv.glb') as unknown as GLTFResult
	const { camera } = useThree()
	const cameraPos = useRef(new Vector3())
	const initialGroupPosition = useRef(new Vector3())
	const savedInitialGroupPos = useRef(false)
	const savedInitialAltScenePos = useRef(false)
	const hasRepositionedForClosing = useRef(false)
	const freezePortalMatrix = useRef(false)
	const propsPositionOffset = useRef(new Vector3())
	const screenMesh = useRef<Mesh>(null)
	const screenQuadCopyRef = useRef(new FullScreenQuad(new ShaderMaterial({
		uniforms: {
			blend: new Uniform(0)
		}
	})))
	const groupRef = useRef<Group>(null)
	const altSceneRef = useRef<Group>(null)
	const portalMaterialRef = useRef<ThreeElements["transitionMaterial"]>(null!)

	const sceneStoreActions = useValue($sceneStoreActions)

	useFramerate(30, () => {
		if (!groupRef.current || !altSceneRef.current) { return }

		// Update blend uniforms
		const sceneBlend = sceneStoreActions.getPlaylistsSceneBlendValue()
		const materialBlend = sceneStoreActions.getPlaylistsMaterialBlendValue()

		if (screenQuadCopyRef.current?.material?.uniforms?.blend) {
			screenQuadCopyRef.current.material.uniforms.blend.value = sceneBlend
		}
		if (portalMaterialRef.current?.uniforms?.blend) {
			portalMaterialRef.current.uniforms.blend.value = materialBlend
		}

		// Read status directly without triggering re-renders
		const playlistsSceneStatus = $sceneStore.playlists.sceneStatus.peek()
		// Calculate target position: initial camera + animation offset + props offset
		const targetVector = new Vector3(
			cameraPos.current.x + 0.15 + propsPositionOffset.current.x,
			cameraPos.current.y + propsPositionOffset.current.y,
			cameraPos.current.z + 1 + propsPositionOffset.current.z
		)

		if (playlistsSceneStatus === "opening") {
			hasRepositionedForClosing.current = false
			freezePortalMatrix.current = false
			if (groupRef.current.position.z >= 3.0) {
				return sceneStoreActions.setPlaylistsSceneStatus("open")
			}
			groupRef.current.position.lerp(targetVector, 0.0075)
			return;
		}
		if (playlistsSceneStatus === "closing") {
			// Position group in front of camera at current position once
			if (!hasRepositionedForClosing.current) {
				// CRITICAL: Freeze portal matrix BEFORE moving the TV
				freezePortalMatrix.current = true

				const currentCameraPos = camera.position
				// Position TV in front of current camera at the "open" z depth
				groupRef.current.position.set(
					currentCameraPos.x + 0.15 + propsPositionOffset.current.x,
					currentCameraPos.y + propsPositionOffset.current.y,
					3.0  // The z position when scene is "open"
				)
				// Also position the alt scene (Spotify logo) to align with camera
				altSceneRef.current.position.set(currentCameraPos.x, currentCameraPos.y, 0)
				hasRepositionedForClosing.current = true
			}

			// Check if we've reached the initial z position
			if (groupRef.current.position.z <= initialGroupPosition.current.z) {
				// Unfreeze portal matrix when animation completes
				freezePortalMatrix.current = false
				return sceneStoreActions.setPlaylistsSceneStatus("closed")
			}

			// Only lerp the z position back, keep x and y locked
			groupRef.current.position.z = groupRef.current.position.z - (groupRef.current.position.z - initialGroupPosition.current.z) * 0.015
			return
		}
	})

	useEffect(() => {
		if (!groupRef.current || savedInitialGroupPos.current) {
			return
		}
		if (!$sceneStore.signInGroupId.peek()) {
			sceneStoreActions.setSignInGroupId(groupRef.current.id)
		}
		initialGroupPosition.current.copy(groupRef.current.position)

		// Store props.position offset for use in animations
		if (props.position) {
			if (props.position instanceof Vector3) {
				propsPositionOffset.current.copy(props.position)
			} else if (Array.isArray(props.position)) {
				propsPositionOffset.current.set(props.position[0], props.position[1], props.position[2])
			}
		}

		savedInitialGroupPos.current = true
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [groupRef])

	useEffect(() => {
		if (!altSceneRef.current || savedInitialAltScenePos.current) {
			return
		}
		if (!$sceneStore.altSceneGroupId.peek()) {
			sceneStoreActions.setAltSceneGroupId(altSceneRef.current.id)
		}
		savedInitialAltScenePos.current = true
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [altSceneRef])

	useEffect(() => {
		if (!camera) { return }
		if (!$sceneStore.camera.peek()) {
			sceneStoreActions.setCamera(camera)
		}
		cameraPos.current.copy(camera.position)
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [camera])

	return (
		<group ref={groupRef} {...props} dispose={null}>
			<mesh geometry={nodes.TV.geometry} material={materials['TV_Chayka-206']} position={[-0.0011, 0.0054, -0.0071]} scale={5.0041} />
			<mesh geometry={nodes.TVSCREEN.geometry} position={[-0.0011, 0.0054, -0.0071]} ref={screenMesh} scale={5.0809}>
				<PortalMaterial
					altScene={
						<group ref={altSceneRef}>
							<SpotifyLogo position={[-0.35, 0, 1]} scale={0.85} />
							<ambientLight intensity={1} />
							<directionalLight intensity={1} position={[5, 5, 5]} />
							<color args={["#05f505"]} attach="background" />
						</group>
					}
					blend={0}
					blur={0.2}
					fragmentShader={frag}
					freezePortalMatrix={freezePortalMatrix}
					ref={portalMaterialRef}
					resolution={1024 as PortalProps["resolution"]}
					screenQuadCopyRef={screenQuadCopyRef}
					side={DoubleSide}
					transitionFragmentShader={transitionFrag}
					transitionVertexShader={transitionVert}
					uniforms={{
						resolution: new Uniform(new Vector2(window.innerWidth, window.innerHeight)),
						uTime: new Uniform(0)
					}}
					vertexShader={vert}
				// wireframe
				>
					<PlaylistsScene />
				</PortalMaterial>
			</mesh>
			<mesh geometry={nodes.TVSCREENBEZEL.geometry} material={materials['TV_Chayka-206']} position={[-0.4388, 1.2966, 0.8396]} scale={[5.1008, 5.1032, 4.9647]} />
		</group>
	)
}

useGLTF.preload('models/tv.glb')
