/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/staging/vintageTelevision.glb -d -t -v -p 4 
*/

import { useValue } from '@legendapp/state/react'
import { RenderTexture, useGLTF } from '@react-three/drei'
import { useControls } from "leva"
import dynamic from 'next/dynamic'
import { useRef, useState } from 'react'
import { type Mesh, type MeshStandardMaterial, Uniform, Vector2 } from 'three'
import { type GLTF } from 'three-stdlib'

import type { GroupProps } from '~/types'

import SpotifyLogo from '~/models/Spotify'
import { $sceneStore } from '~/stores/scene'

import Playlists from '../Canvas/Playlists'
import PortalMaterial from "../PortalMaterial"
import frag from "../TransitionMaterial/frag.glsl"
import vert from "../TransitionMaterial/vert.glsl"
import PlaylistsScene from './Playlists'

const TransitionMaterial = dynamic(() => import("../TransitionMaterial"), { ssr: false })

type GLTFResult = GLTF & {
	materials: {
		['TV_Chayka-206']: MeshStandardMaterial
	}
	nodes: {
		TV: Mesh
		TVSCREEN: Mesh
		TVSCREENBEZEL: Mesh
	}
}

export default function InitialScene(props: GroupProps) {
	const { materials, nodes } = useGLTF('models/tv.glb') as unknown as GLTFResult
	const transitionProgress = useValue($sceneStore.sceneDepth.transitionProgress)
	const screenMesh = useRef<Mesh>(null)
	const [blend, setBlend] = useState(0)

	useControls({
		progress: {
			max: 1, min: 0, onChange: (v: number) => {
				transitionProgress.set(v)
				setBlend(v)
			}, value: 0
		}
	})

	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.TV.geometry} material={materials['TV_Chayka-206']} position={[-0.0011, 0.0054, -0.0071]} scale={5.0041} />
			<mesh geometry={nodes.TVSCREEN.geometry} position={[-0.0011, 0.0054, -0.0071]} ref={screenMesh} scale={5.0809}>
				{/* <TransitionMaterial> */}
				{/* 	<RenderTexture attach="uTextureA"> */}
				{/* 		<SpotifyLogo position={[1.3, -1.25, 1]} rotation={[0, 0, 3 * Math.PI / 2 + 0.15]} scale={0.85} /> */}
				{/* 		<ambientLight intensity={100} /> */}
				{/* 		<directionalLight intensity={1} position={[5, 5, 5]} /> */}
				{/* 	</RenderTexture> */}
				{/* 	<RenderTexture attach="uTextureB"> */}
				{/* 		<PlaylistsScene /> */}
				{/* 	</RenderTexture> */}
				{/* </TransitionMaterial> */}
				<PortalMaterial
					// altScene={
					// <RenderTexture attach="uTextureA">
					// <SpotifyLogo position={[1.3, -1.25, 1]} rotation={[0, 0, 3 * Math.PI / 2 + 0.15]} scale={0.85} />
					// <ambientLight intensity={100} />
					// <directionalLight intensity={1} position={[5, 5, 5]} />
					// <color args={["#05f505"]} attach="background" />
					// </RenderTexture>
					// }
					blend={blend}
					blur={0.2}
					// fragmentShader={frag}
					// portalSceneRenderTarget="uTextureB"
					// glslVersion="300 es"
					resolution={1024}
					uniforms={{
						uResolution: new Uniform(new Vector2(window.innerWidth, window.innerHeight)),
						uTime: new Uniform(0)
					}}
				// vertexShader={vert}
				>
					<PlaylistsScene />
				</PortalMaterial>
			</mesh>
			<mesh geometry={nodes.TVSCREENBEZEL.geometry} material={materials['TV_Chayka-206']} position={[-0.4388, 1.2966, 0.8396]} scale={[5.1008, 5.1032, 4.9647]} />
		</group>
	)
}

useGLTF.preload('models/tv.glb')
