/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/staging/vintageTelevision.glb -d -t -v -p 4 
*/

import { Box, MeshPortalMaterial, useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { type Mesh, MeshStandardMaterial } from 'three'
import { type GLTF } from 'three-stdlib'

import type { GroupProps } from '~/types'

import CameraShake from './CameraShake'

type GLTFResult = GLTF & {
	materials: {
		['TV_Chayka-206']: MeshStandardMaterial
	}
	nodes: {
		TV: Mesh
		TVSCREEN: Mesh
		TVSCREENBEZEL: Mesh
	}
}

export default function SignInTV(props: GroupProps) {
	const { materials, nodes } = useGLTF('tv.glb') as unknown as GLTFResult
	const screenMesh = useRef(null)
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.TV.geometry} material={materials['TV_Chayka-206']} position={[-0.0011, 0.0054, -0.0071]} scale={5.0041} />
			<mesh geometry={nodes.TVSCREEN.geometry} position={[-0.0011, 0.0054, -0.0071]} ref={screenMesh} scale={5.0809}>
				<MeshPortalMaterial blur={0.2} resolution={1024}>
					<Box args={[0.1, 0.1, 0.1]} material={new MeshStandardMaterial({ color: "green" })} position={[-0.1, 0.2, 0]} />
					<ambientLight intensity={1} />
					<CameraShake />
				</MeshPortalMaterial>
			</mesh>
			<mesh geometry={nodes.TVSCREENBEZEL.geometry} material={materials['TV_Chayka-206']} position={[-0.4388, 1.2966, 0.8396]} scale={[5.1008, 5.1032, 4.9647]} />
		</group>
	)
}

useGLTF.preload('tv.glb')
