/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/staging/vintageTelevision.glb -d -t -v -p 4 
*/

import { Box, Html, MeshPortalMaterial, useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { type Mesh, MeshStandardMaterial } from 'three'
import { type GLTF } from 'three-stdlib'

import type { GroupProps } from '~/types'

import AuthCard from '~/app/(frontend)/auth/[pathname]/view'
import { Button } from '~/ui/button'

import CameraShake from './CameraShake'

type GLTFResult = GLTF & {
	materials: {
		['TV_Chayka-206']: MeshStandardMaterial
	}
	nodes: {
		TV: Mesh
		TVSCREEN: Mesh
		TVSCREENBEZEL: Mesh
	}
}

export default function SignInTV(props: GroupProps) {
	const { materials, nodes } = useGLTF('tv.glb') as unknown as GLTFResult
	const screenMesh = useRef(null)
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.TV.geometry} material={materials['TV_Chayka-206']} position={[-0.0011, 0.0054, -0.0071]} scale={5.0041} />
			<mesh geometry={nodes.TVSCREEN.geometry} position={[-0.0011, 0.0054, -0.0071]} ref={screenMesh} scale={5.0809}>
				<MeshPortalMaterial>
					<Box args={[0.1, 0.1, 0.1]} material={new MeshStandardMaterial({ color: "green" })} position={[-0.1, 0.2, 0]} />
					<ambientLight intensity={1} />
					<CameraShake />
				</MeshPortalMaterial>
				{/* <Html */}
				{/* 	center */}
				{/* 	className="w-116 bg-black h-104 rounded-xl grid place-items-center text-center" */}
				{/* 	distanceFactor={0.5} */}
				{/* 	occlude="blending" */}
				{/* 	position={[-0.105, 0.25, 0.01]} */}
				{/* 	transform */}
				{/* > */}
				{/* 	<div> */}
				{/* 		<h1 className="text-white">hello dom from canvas</h1> */}
				{/* 		<Button>SignIn</Button> */}
				{/* 	</div> */}
				{/* </Html> */}
			</mesh>
			<mesh geometry={nodes.TVSCREENBEZEL.geometry} material={materials['TV_Chayka-206']} position={[-0.4388, 1.2966, 0.8396]} scale={[5.1008, 5.1032, 4.9647]} />
		</group>
	)
}

useGLTF.preload('tv.glb')
