/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/staging/vintageTelevision.glb -d -t -v -p 4 
*/

import { useValue } from '@legendapp/state/react'
import { Instance, Instances, type InstancesProps, useGLTF } from '@react-three/drei'
import { useEffect, useRef } from 'react'
import { type AnimationClip, Box3, type Group, type Mesh, type MeshStandardMaterial, type ShaderMaterial, Uniform, Vector2, Vector3 } from 'three'
import { type GLTF } from 'three-stdlib'

import { useFramerate } from '~/hooks/useFramerate'
import { $sceneStoreActions } from '~/stores/scene'
import { $spotifyStore } from '~/stores/spotify'

import frag from "./frag.glsl"
import InstancedScreenMaterial from './InstancedShaderMaterial'
import { usePlaylistsTextureArray } from './usePlaylistsTextureArray'
import vert from "./vert.glsl"

type GLTFResult = GLTF & {
	animations: AnimationClip[]
	materials: {
		['TV_Chayka-206']: MeshStandardMaterial
	}
	nodes: {
		TV: Mesh
		TVSCREEN: Mesh
		TVSCREENBEZEL: Mesh
	}
}

export const GAPX = 4;
export const GAPY = 3;
export const ROW_LENGTH = 10;

export default function InstancedVintageTelevision({ ...groupProps }: Partial<InstancesProps>) {
	const playlists = useValue($spotifyStore.userPlaylists)
	const sceneStoreActions = useValue($sceneStoreActions)
	const { materials, nodes } = useGLTF(`models/tv.glb`) as unknown as GLTFResult
	const groupRef = useRef<Group>(null)
	const shaderMaterial = useRef<ShaderMaterial>(null)

	const centerX = ROW_LENGTH * GAPX / 2
	const maxRows = Math.floor(playlists.length / ROW_LENGTH)
	const centerY = maxRows * GAPY / 2
	const playlistsWithImages = playlists.filter((p) => p.images !== null && p.images.length > 0)

	const textureArray = usePlaylistsTextureArray(playlists)

	useEffect(() => {
		if (!groupRef.current) { return }
		const groupBoundingBox = new Box3().setFromObject(groupRef.current)
		const gbbs = groupBoundingBox.getSize(new Vector3())
		console.log('group bounding box: ', groupBoundingBox.min, groupBoundingBox.max)
		console.log('gbbs: ', gbbs)
		const offset = 5
		sceneStoreActions.setPlaylistsCameraBounds({
			maxX: groupBoundingBox.max.x - offset,
			maxY: groupBoundingBox.max.y - offset,
			minX: groupBoundingBox.min.x + offset,
			minY: groupBoundingBox.min.y + offset
		})
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [groupRef?.current])

	useFramerate(30, () => {
		if (!shaderMaterial.current) { return };
		shaderMaterial.current.uniforms.uTime!.value += 0.01
	})

	if (!textureArray) {
		return null // Don't render until texture is ready
	}

	return (
		<group ref={groupRef} {...groupProps}>
			<Instances dispose={null} frustumCulled={false} geometry={nodes.TV.geometry} material={materials["TV_Chayka-206"]}>
				{playlistsWithImages.map((p, i) => {
					return (
						<Instance
							key={`tv-body-instance-${i}`}
							position={[i % ROW_LENGTH * GAPX - 0.0011 - centerX, Math.floor(i / ROW_LENGTH) * -GAPY + 0.0054 + centerY, -0.0071]}
							scale={5.0041}
						/>
					)
				})}
			</Instances>
			<Instances frustumCulled={false} geometry={nodes.TVSCREEN.geometry}>
				<shaderMaterial
					fragmentShader={frag}
					glslVersion="300 es"
					ref={shaderMaterial}
					uniforms={{
						uResolution: new Uniform(new Vector2(window.innerWidth, window.innerHeight)),
						uTextureArray: new Uniform(textureArray),
						uTime: new Uniform(0)
					}}
					vertexShader={vert}
				/>
				{playlistsWithImages.map((p, i) => {
					return <InstancedScreenMaterial index={i} key={`tv-screen-instance-${i}`} playlist={p} playlistCount={playlists.length} />
				})}
			</Instances>
			<Instances frustumCulled={false} geometry={nodes.TVSCREENBEZEL.geometry} material={materials["TV_Chayka-206"]}>
				{playlistsWithImages.map((p, i) => {
					return (
						<Instance
							key={`tv-bezel-instance-${i}`}
							position={[i % ROW_LENGTH * GAPX - 0.4388 - centerX, Math.floor(i / ROW_LENGTH) * -GAPY + 1.2966 + centerY, 0.8396]}
							scale={[5.1008, 5.1032, 4.9647]}
						/>
					)
				})}
			</Instances>
		</group>
	)
}

useGLTF.preload('models/tv.glb')
