import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import SceneLoader from "~/components/Canvas/SceneLoader";
import ClientProviders from "~/components/Providers/client";
import ServerProviders from "~/components/Providers/server";

export const metadata: Metadata = {
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
	title: "Create T3 App",
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	auth,
	children,
}: Readonly<{ auth: React.ReactNode; children: React.ReactNode }>) {
	return (
		<html className={`${geist.variable}`} lang="en">
			<body className="bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<ServerProviders>
					<ClientProviders>
						{children}
						{auth}
						<SceneLoader />
					</ClientProviders>
				</ServerProviders>
			</body>
		</html>
	);
}
