/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/spotify.glb -d -t -v -p 4 
Author: leesokleng (https://sketchfab.com/leesokleng)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spotify-logo-090826d4a192443c89453cf256b9270e
Title: Spotify Logo
*/

import { useValue } from '@legendapp/state/react'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { type Group, type Mesh, type MeshStandardMaterial } from 'three'
import { type GLTF } from 'three-stdlib'

import type { GroupProps } from '~/types'

import { useSession } from '~/auth/client'
import { useFramerate } from '~/hooks/useFramerate'
import { $sceneStore } from '~/stores/scene'

type GLTFResult = GLTF & {
	materials: {
		material: MeshStandardMaterial
	}
	nodes: {
		Cap_1_Mat_0: Mesh
		Cap_2_Mat_0: Mesh
		Extrude_Mat_0: Mesh
		Rounding_1_Mat_0: Mesh
		Rounding_2_Mat_0: Mesh
	}
}

export default function SpotifyLogo({ ...groupProps }: GroupProps & { rotate?: boolean }) {
	const { materials, nodes } = useGLTF('models/spotify.glb') as unknown as GLTFResult
	const { data: auth } = useSession()
	const playlistsSceneStatus = useValue($sceneStore.playlists.sceneStatus)
	const groupRef = useRef<Group>(null)

	useFramerate(30, () => {
		if (!groupRef.current || !auth?.session) { return }
		if (playlistsSceneStatus === "closing") {
			console.log('closing...')
			groupRef.current.rotation.z = 0
		} else {
			console.log('loading...')
			groupRef.current.rotation.z -= 0.025
		}
	})

	return (
		<group {...groupProps} dispose={null} ref={groupRef}>
			<group scale={0.01}>
				<mesh geometry={nodes.Extrude_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Rounding_1_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Cap_1_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Rounding_2_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Cap_2_Mat_0.geometry} material={materials.material} />
			</group>
		</group>
	)
}

useGLTF.preload('models/spotify.glb')
