/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/spotify.glb -d -t -v -p 4 
Author: leesokleng (https://sketchfab.com/leesokleng)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spotify-logo-090826d4a192443c89453cf256b9270e
Title: Spotify Logo
*/

import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { type Group, type Mesh, type MeshStandardMaterial } from 'three'
import { type GLTF } from 'three-stdlib'

import type { GroupProps } from '~/types'

import { useFramerate } from '~/hooks/useFramerate'

type GLTFResult = GLTF & {
	materials: {
		material: MeshStandardMaterial
	}
	nodes: {
		Cap_1_Mat_0: Mesh
		Cap_2_Mat_0: Mesh
		Extrude_Mat_0: Mesh
		Rounding_1_Mat_0: Mesh
		Rounding_2_Mat_0: Mesh
	}
}

export default function SpotifyLogo(props: GroupProps) {
	const { materials, nodes } = useGLTF('models/spotify.glb') as unknown as GLTFResult
	const groupRef = useRef<Group>(null)

	// useFramerate(30, () => {
	// 	if (!groupRef.current) { return; }
	// 	groupRef.current.rotation.x += 0.025
	// })

	return (
		<group {...props} dispose={null} ref={groupRef}>
			<group scale={0.01}>
				<mesh geometry={nodes.Extrude_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Rounding_1_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Cap_1_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Rounding_2_Mat_0.geometry} material={materials.material} />
				<mesh geometry={nodes.Cap_2_Mat_0.geometry} material={materials.material} />
			</group>
		</group>
	)
}

useGLTF.preload('models/spotify.glb')
